"""empty message

Revision ID: 261a9686768d
Revises: 578d79a07156
Create Date: 2020-08-07 14:44:22.997398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261a9686768d'
down_revision = '578d79a07156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('stage', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'stage')
    # ### end Alembic commands ###
