"""empty message

Revision ID: 5b4e1146fb1c
Revises: 9b192c383e48
Create Date: 2020-08-16 12:15:31.631775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b4e1146fb1c'
down_revision = '9b192c383e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section', 'label')
    # ### end Alembic commands ###
