"""empty message

Revision ID: 9b192c383e48
Revises: cda3e16db65c
Create Date: 2020-08-14 20:34:19.327881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b192c383e48'
down_revision = 'cda3e16db65c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('thesis', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'thesis')
    # ### end Alembic commands ###
