"""empty message

Revision ID: 9f09d20feccf
Revises: eb6335f7b117
Create Date: 2020-08-24 14:17:36.906323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f09d20feccf'
down_revision = 'eb6335f7b117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section', 'title')
    # ### end Alembic commands ###
