"""empty message

Revision ID: eb6335f7b117
Revises: 2e1eb1c9c4db
Create Date: 2020-08-18 11:08:29.063022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb6335f7b117'
down_revision = '2e1eb1c9c4db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('last_edit', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_project_last_edit'), 'project', ['last_edit'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_last_edit'), table_name='project')
    op.drop_column('project', 'last_edit')
    # ### end Alembic commands ###
